package org.rmmcosta

fun main() {
    println("Hello World!")
    val mc1 = Machine(1)
    val mc2 = Machine(2)
    val mc3 = Machine(3)
    val root = MachineComposite(listOf(mc1, mc2, mc3), 44)
    val machineCountingVisitor = MachineCountingVisitor()
    root.accept(machineCountingVisitor)
    println(machineCountingVisitor.count())
    val machine100 = Machine(100)
    machine100.accept(machineCountingVisitor)
    println(machineCountingVisitor.count())
    println(FindVisitor.find(machine100, 100))
    println(FindVisitor.find(machine100, 101))
    println("find 1 inside composite")
    println(FindVisitor.find(root, 1))
    println("find 2 inside composite")
    println(FindVisitor.find(root, 2))
    println("find 3 inside composite")
    println(FindVisitor.find(root, 3))
    println("find 4 inside composite")
    println(FindVisitor.find(root, 4))
}
